name: Deploy RustDesk (Terragrunt)

on:
  pull_request:
    paths:
      - 'infra/**'
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  plan:
    name: Terragrunt Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      # Optional Terraform variable overrides (set these as repo secrets if you need to override module inputs)
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_ssh_keys: ${{ secrets.TF_VAR_SSH_KEYS }}
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_size: ${{ secrets.TF_VAR_size }}
      TF_VAR_image: ${{ secrets.TF_VAR_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Install Terragrunt
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          TG_VERSION=0.55.17
          wget -qO /tmp/terragrunt.zip https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          sudo install -m 0755 /tmp/terragrunt.zip /usr/local/bin/terragrunt

      - name: Run Terragrunt Plan
        working-directory: infra/live/dev/rustdesk
        run: |
          terragrunt init --terragrunt-non-interactive
          terragrunt plan --terragrunt-non-interactive

  apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      # Optional Terraform variable overrides (set these as repo secrets if you need to override module inputs)
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_ssh_keys: ${{ secrets.TF_VAR_SSH_KEYS }}
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_size: ${{ secrets.TF_VAR_size }}
      TF_VAR_image: ${{ secrets.TF_VAR_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Install Terragrunt
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          TG_VERSION=0.55.17
          wget -qO /tmp/terragrunt.zip https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          sudo install -m 0755 /tmp/terragrunt.zip /usr/local/bin/terragrunt

      - name: Terragrunt Apply
        working-directory: infra/live/dev/rustdesk
        run: |
          terragrunt init --terragrunt-non-interactive
          terragrunt apply --auto-approve --terragrunt-non-interactive
